version: '3'

services:
  database:
    image: mariadb:10.7.1-focal
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '0.0.0.0:3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: codes
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
      - db-data:/var/lib/mysql:rw
    networks:
      csvuploader:

  php:
    image: php:7.4-cli
    command: php -t /app -S 0.0.0.0:8085
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - ./index.html:/app/index.html
      - ./uploader.php:/app/uploader.php
    ports:
      - "0.0.0.0:8085:8085"
    networks:
      csvuploader:

networks:
  csvuploader:
    driver: bridge

volumes:
  db-data:
